#!/usr/bin/env bash
#creating a script that uses a if statement
x=1                                                                   
while [ $x -le 10 ]                                                              
do   
	echo "Best School" 	
	if [ $X -eq 9 ]   
then  
	echo "hi"
	fi
	x=$(( x + 1 )) 
done        
